apiVersion: v1
kind: PersistentVolume
metadata:
  name: leagueledger-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: leagueledger-local
  hostPath:
    path: /var/local/leagueledger-postgres
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: leagueledger
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: leagueledger-local
  resources:
    requests:
      storage: 1Gi
